name: ebmb.me
favicon: null
layout_spectrum: 1
typography_spectrum: 1
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#cbcbcb'
    - '#5b5b5b'
    - '#939393'
  brandStrength: 1
  lightness: 0.0625
  saturation: 0.1875
  rhythmicContrast: 0.9208045662380755
purpose: []
