name: ebmb.me
favicon: null
layout_spectrum: 0.25094514549709857
typography_spectrum: 0.28034004755318165
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#7f7f7f'
    - '#333333'
    - '#adadad'
  brandStrength: 1
  lightness: 0.10626466618850827
  saturation: 0.1929393233731389
  rhythmicContrast: 0.9208045662380755
purpose: []
